dist:
  name: profiling-collector
  description: Profiling OTel Collector distribution
  output_path: ./collector

processors:
  - gomod:
      go.opentelemetry.io/collector-contrib/processor/resourcedetectionprocessor v0.116.0

exporters:
  - gomod:
      go.opentelemetry.io/collector/exporter/debugexporter v0.116.0

receivers:
  - gomod: go.opentelemetry.io/ebpf-profiler v0.0.1
    import: go.opentelemetry.io/ebpf-profiler/collector
    name: profilesreceiver
    path: ../../open-telemetry/opentelemetry-ebpf-profiler
