dist:
  name: profiling-collector
  description: Profiling OTel Collector distribution
  output_path: ./collector
  otelcol_version: 0.109.0

exporters:
  - gomod:
      go.opentelemetry.io/collector/exporter/debugexporter v0.109.0
  - gomod: github.com/dmathieu/tmp-profiles-collector/stdoutexporter v0.0.1
    path: ./stdoutexporter
  - gomod:
      go.opentelemetry.io/collector/exporter/otlpexporter v0.109.0

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.109.0

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.109.0
  - gomod: go.opentelemetry.io/ebpf-profiler v0.0.1
    import: go.opentelemetry.io/ebpf-profiler/collector
    name: profilesreceiver
    path: ../../open-telemetry/opentelemetry-ebpf-profiler
