receivers:
  otelreceiver: # this line represents the ID of your receiver
    project-id: '123'
    collection-agent: 127.0.0.1:11000
    verbose: true
    disable-tls: true
    secret-token: abc123

exporters:
  stdout:

service:
  pipelines:
    profiles:
      receivers: [ otelreceiver ]
      processors: [ ]
      exporters: [ stdout ]
  telemetry:
    logs:
      level: debug
