receivers:
  profiling:
    SamplesPerSecond: 19

processors:
  resourcedetection:
    detectors: [ system ]
    system:
      hostname_sources: [ "os" ]
      resource_attributes:
        host.id:
          enabled: true
        host.name:
          enabled: true
        os.type:
          enabled: true

exporters:
  debug:
  otlp:
    endpoint: localhost:11000
    tls:
      insecure: true

service:
  pipelines:
    profiles:
      receivers: [ profiling ]
      processors: [ resourcedetection ]
      exporters: [ debug, otlp ]
  telemetry:
    logs:
      level: debug
