receivers:
  otelreceiver:

exporters:
  debug:

service:
  pipelines:
    profiles:
      receivers: [ otelreceiver ]
      processors: [ ]
      exporters: [ debug ]
  telemetry:
    logs:
      level: debug
