receivers:
  profiling:
    SamplesPerSecond: 100

exporters:
  debug:

service:
  pipelines:
    profiles:
      receivers: [ profiling ]
      processors: [ ]
      exporters: [ debug ]
  telemetry:
    logs:
      level: debug
