---
receivers:
  profiling:
    samples_per_second: 19

processors:
  resourcedetection:
    detectors: [system]
    system:
      hostname_sources: ["os"]
      resource_attributes:
        host.id:
          enabled: true
        host.name:
          enabled: true
        os.type:
          enabled: true

exporters:
  debug:
  elasticsearch:
    endpoint:  # REPLACE WITH YOUR ES ENDPOINT
    api_key:  # REPLACE WITH YOUR API
    mapping:
      mode: otel

service:
  pipelines:
    profiles:
      receivers: [profiling]
      processors: [resourcedetection]
      exporters: [elasticsearch]
  telemetry:
    logs:
      level: debug
